project_name: norden
builds:
  - id: default
    main: ./cmd/norden
    binary: norden
    flags:
      - -tags
      - netgo release
      - -trimpath
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/xrelkd/norden/pkg/version.AppName={{.ProjectName}} -X github.com/xrelkd/norden/pkg/version.Version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"

archives:
  - id: default
    builds:
      - default
    name_template: "norden_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
